# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx

language: r

cache: packages

before_install:
  - Rscript -e 'if (!require("covr")) install.packages("covr")'

after_success:
  - Rscript -e 'pkgdown::build("jeksterslabPkg")'
  - Rscript -e 'covr::codecov()'

deploy:
  provider: pages
  skip-cleaning: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    brach: master
