# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
- linux
- osx
disable_homebrew: true
language: r
cache: packages
r:
- devel
- release
- oldrel
jobs:
  exclude:
  - r: devel
    os: osx
before_install:
- Rscript -e 'if (!require("covr")) install.packages("covr")'
- Rscript -e 'if (!require("pkgdown")) install.packages("pkgdown")'
after_success:
- >-
  if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_R_VERSION_STRING" = "release" ]; then
    echo Code coverage...
    Rscript -e 'covr::codecov()'
    Rscript -e 'pkgdown::build_site()'
  else
    echo Skip code coverage
  fi
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  token: "$GITHUB_PAT"
  keep_history: true
  local_dir: docs
  on:
    branch: master
