# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx
language: r
cache: packages

r_packages:
  - covr

r_github_packages:
  - jeksterslabds/jeksterslabRutils

after_success:
  - Rscript -e 'library(covr); codecov()'
  