#' Create a Boilerplate Package `Rd` Function Documentation.
#'
#' Note that if [jeksterslabRpkg::pkg_create()] is used,
#' this function will be called.
#'
#' If you are going to document, check, and build your package using `devtools`,
#' you may delete the `Rd` function documentation file generated by this function.
#'
#' @author Ivan Jacob Agaloos Pesigan
#' @inheritParams pkg_description
#' @examples
#' \dontrun{
#' pkg_rd(
#'   pkg_dir = getwd(),
#'   pkg_name = "boilerplatePackage"
#' )
#' }
#' @export
pkg_rd <- function(pkg_dir = getwd(),
                   pkg_name) {
  man <- file.path(
    pkg_dir,
    pkg_name,
    "man"
  )
  output <- paste0(
    readLines(
      con = system.file(
        "extdata",
        "zRd",
        package = "jeksterslabRpkg",
        mustWork = TRUE
      )
    ),
    collapse = "\n"
  )
  output <- paste0(
    "% This is a boilerplate example.",
    "\n",
    "% Delete this file if you are building documentation files with roxygen.",
    "\n",
    output
  )
  util_txt2file(
    text = output,
    dir = man,
    fn = "z.Rd"
  )
}
